### ISSUE TITLE
Namespace Grant?

### ISSUE THREAD

**Issue by doublejosh** [grouchojs/groucho#8]
Hello @DoodlingDev

Curious if you might be willing to give up the `grouchojs` org namespace to use for this repo...
https://github.com/tableau-mkt/groucho

I'd like to transition it to a more truly open-source project (without a sponsoring company) as it will be used at several organizations.

Thanks.

**Comment by DoodlingDev** [comment]
I've recently come back into some time to work on this project, so sorry it's been sitting in the npm name for "groucho".

I'm also not sure though that npm is the right place to hold my groucho, because it's less a package and more standalone app. I'm happy to remove my groucho from npm for you.
